-- FOC 2026 Album: schema + RLS + RPC base
-- Rodar no SQL editor do Supabase depois de criar os usuários em Auth.

create extension if not exists pgcrypto;

create or replace function public.foc2026_current_username()
returns text
language sql
stable
as $$
  select coalesce(
    nullif(auth.jwt() -> 'user_metadata' ->> 'username', ''),
    nullif(auth.jwt() ->> 'email', '')
  )
$$;

create table if not exists public.foc2026_players (
  username text primary key,
  name text not null,
  is_admin boolean not null default false,
  pack_opened boolean not null default false,
  created_at timestamptz not null default now(),
  serie text
);

create table if not exists public.foc2026_rounds (
  number int primary key,
  name text not null,
  starts_at timestamptz,
  deadline timestamptz,
  sas_limit int,
  active boolean not null default false
);

create table if not exists public.foc2026_matches (
  id text primary key,
  round_number int not null references public.foc2026_rounds(number) on delete cascade,
  player_a_username text not null references public.foc2026_players(username),
  player_b_username text not null references public.foc2026_players(username),
  player_a_houses text,
  player_b_houses text,
  player_a_keys int not null default 0 check (player_a_keys between 0 and 3),
  player_b_keys int not null default 0 check (player_b_keys between 0 and 3),
  player_a_reported boolean not null default false,
  player_b_reported boolean not null default false,
  confirmed_at timestamptz,
  player_a_picks_completed boolean not null default false,
  player_b_picks_completed boolean not null default false,
  fallback_active boolean not null default false,
  match_deadline_passed boolean not null default false,
  completed boolean not null default false,
  check (player_a_username <> player_b_username)
);

create unique index if not exists foc2026_one_match_as_a_per_round
  on public.foc2026_matches(round_number, player_a_username);

create unique index if not exists foc2026_one_match_as_b_per_round
  on public.foc2026_matches(round_number, player_b_username);

create table if not exists public.foc2026_collections (
  player_username text not null references public.foc2026_players(username) on delete cascade,
  sticker_id text not null,
  quantity int not null default 1 check (quantity > 0),
  source text not null check (source in ('pack', 'pick', 'challenge', 'admin')),
  is_new boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (player_username, sticker_id)
);

create table if not exists public.foc2026_challenges (
  player_username text not null references public.foc2026_players(username) on delete cascade,
  id text not null,
  title text not null,
  description text not null,
  completed boolean not null default false,
  pending_validation boolean not null default false,
  picked_id text,
  primary key (player_username, id)
);

create table if not exists public.foc2026_admin_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message text not null
);

create table if not exists public.foc2026_stickers_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  player_username text references public.foc2026_players(username),
  round_number int,
  message text not null,
  type text not null check (type in ('pack', 'pick', 'challenge', 'admin', 'info'))
);

create or replace function public.foc2026_is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.foc2026_players
    where username = public.foc2026_current_username()
      and is_admin = true
  )
$$;

alter table public.foc2026_players enable row level security;
alter table public.foc2026_rounds enable row level security;
alter table public.foc2026_matches enable row level security;
alter table public.foc2026_collections enable row level security;
alter table public.foc2026_challenges enable row level security;
alter table public.foc2026_admin_logs enable row level security;
alter table public.foc2026_stickers_log enable row level security;

drop policy if exists "players read all" on public.foc2026_players;
create policy "players read all" on public.foc2026_players
for select using (true);

drop policy if exists "players update self" on public.foc2026_players;
create policy "players update self" on public.foc2026_players
for update using (username = public.foc2026_current_username())
with check (username = public.foc2026_current_username());

drop policy if exists "rounds read all" on public.foc2026_rounds;
create policy "rounds read all" on public.foc2026_rounds
for select using (true);

drop policy if exists "rounds admin write" on public.foc2026_rounds;
create policy "rounds admin write" on public.foc2026_rounds
for all using (public.foc2026_is_admin())
with check (public.foc2026_is_admin());

drop policy if exists "matches read participants" on public.foc2026_matches;
create policy "matches read participants" on public.foc2026_matches
for select using (
  public.foc2026_is_admin()
  or public.foc2026_current_username() in (player_a_username, player_b_username)
);

drop policy if exists "matches admin write" on public.foc2026_matches;
create policy "matches admin write" on public.foc2026_matches
for all using (public.foc2026_is_admin())
with check (public.foc2026_is_admin());

drop policy if exists "collections read all" on public.foc2026_collections;
create policy "collections read all" on public.foc2026_collections
for select using (true);

drop policy if exists "collections admin write" on public.foc2026_collections;
create policy "collections admin write" on public.foc2026_collections
for all using (public.foc2026_is_admin())
with check (public.foc2026_is_admin());

drop policy if exists "challenges read self or admin" on public.foc2026_challenges;
create policy "challenges read self or admin" on public.foc2026_challenges
for select using (
  public.foc2026_is_admin()
  or player_username = public.foc2026_current_username()
);

drop policy if exists "challenges admin write" on public.foc2026_challenges;
create policy "challenges admin write" on public.foc2026_challenges
for all using (public.foc2026_is_admin())
with check (public.foc2026_is_admin());

drop policy if exists "admin logs read admin" on public.foc2026_admin_logs;
create policy "admin logs read admin" on public.foc2026_admin_logs
for select using (public.foc2026_is_admin());

drop policy if exists "stickers log read all" on public.foc2026_stickers_log;
create policy "stickers log read all" on public.foc2026_stickers_log
for select using (true);

create or replace function public.foc2026_upsert_collection(
  p_username text,
  p_sticker_id text,
  p_source text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.foc2026_collections(player_username, sticker_id, quantity, source, is_new, updated_at)
  values (p_username, p_sticker_id, 1, p_source, true, now())
  on conflict (player_username, sticker_id)
  do update set
    quantity = foc2026_collections.quantity + 1,
    source = excluded.source,
    is_new = true,
    updated_at = now();
end;
$$;

create or replace function public.foc2026_open_pack(
  p_sticker_ids text[],
  p_pack_type text,
  p_round_number int
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.foc2026_current_username();
  v_player_name text;
  v_sticker text;
begin
  if v_username is null then
    raise exception 'not authenticated';
  end if;

  select name into v_player_name from public.foc2026_players where username = v_username;

  if p_pack_type = 'crest' and not public.foc2026_is_admin() then
    raise exception 'crest packs are disabled for players';
  end if;

  if p_pack_type = 'player' then
    update public.foc2026_players set pack_opened = true where username = v_username;
  end if;

  foreach v_sticker in array p_sticker_ids loop
    perform public.foc2026_upsert_collection(v_username, v_sticker, 'pack');
    insert into public.foc2026_stickers_log(player_username, round_number, message, type)
    values (
      v_username,
      p_round_number,
      coalesce(v_player_name, v_username) || ' obteve a figurinha ' || v_sticker || ' via ' ||
        case when p_pack_type = 'crest' then 'Pacotinho dourado' else 'Pacotinho inicial' end,
      'pack'
    );
  end loop;
end;
$$;

create or replace function public.foc2026_submit_houses(
  p_match_id text,
  p_houses text[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.foc2026_current_username();
  v_match public.foc2026_matches%rowtype;
begin
  if array_length(p_houses, 1) <> 3 then
    raise exception 'exactly 3 houses required';
  end if;

  select * into v_match from public.foc2026_matches where id = p_match_id;
  if not found or v_username not in (v_match.player_a_username, v_match.player_b_username) then
    raise exception 'match not found for user';
  end if;

  if v_username = v_match.player_a_username then
    update public.foc2026_matches set player_a_houses = array_to_string(p_houses, ',') where id = p_match_id;
  else
    update public.foc2026_matches set player_b_houses = array_to_string(p_houses, ',') where id = p_match_id;
  end if;
end;
$$;

create or replace function public.foc2026_report_own_keys(
  p_match_id text,
  p_keys int
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.foc2026_current_username();
  v_match public.foc2026_matches%rowtype;
begin
  if p_keys < 0 or p_keys > 3 then
    raise exception 'keys must be between 0 and 3';
  end if;

  select * into v_match from public.foc2026_matches where id = p_match_id for update;
  if not found or v_username not in (v_match.player_a_username, v_match.player_b_username) then
    raise exception 'match not found for user';
  end if;

  if v_username = v_match.player_a_username then
    update public.foc2026_matches
    set player_a_keys = p_keys,
        player_a_reported = true,
        player_a_picks_completed = false,
        completed = false
    where id = p_match_id;
  else
    update public.foc2026_matches
    set player_b_keys = p_keys,
        player_b_reported = true,
        player_b_picks_completed = false,
        completed = false
    where id = p_match_id;
  end if;

  update public.foc2026_matches
  set confirmed_at = now()
  where id = p_match_id
    and player_a_reported = true
    and player_b_reported = true
    and confirmed_at is null;
end;
$$;

create or replace function public.foc2026_reopen_own_report(p_match_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.foc2026_current_username();
  v_match public.foc2026_matches%rowtype;
begin
  select * into v_match from public.foc2026_matches where id = p_match_id for update;
  if not found or v_username not in (v_match.player_a_username, v_match.player_b_username) then
    raise exception 'match not found for user';
  end if;
  if v_match.completed then
    raise exception 'completed match cannot be reopened';
  end if;

  if v_username = v_match.player_a_username then
    update public.foc2026_matches
    set player_a_reported = false,
        player_a_picks_completed = false,
        confirmed_at = null,
        completed = false
    where id = p_match_id;
  else
    update public.foc2026_matches
    set player_b_reported = false,
        player_b_picks_completed = false,
        confirmed_at = null,
        completed = false
    where id = p_match_id;
  end if;
end;
$$;

create or replace function public.foc2026_claim_picks(
  p_match_id text,
  p_sticker_ids text[],
  p_round_number int
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.foc2026_current_username();
  v_player_name text;
  v_match public.foc2026_matches%rowtype;
  v_sticker text;
begin
  select * into v_match from public.foc2026_matches where id = p_match_id for update;
  if not found or v_username not in (v_match.player_a_username, v_match.player_b_username) then
    raise exception 'match not found for user';
  end if;
  if not (v_match.player_a_reported and v_match.player_b_reported) then
    raise exception 'picks are locked until both reports are submitted';
  end if;

  select name into v_player_name from public.foc2026_players where username = v_username;

  foreach v_sticker in array p_sticker_ids loop
    perform public.foc2026_upsert_collection(v_username, v_sticker, 'pick');
    insert into public.foc2026_stickers_log(player_username, round_number, message, type)
    values (
      v_username,
      p_round_number,
      coalesce(v_player_name, v_username) || ' obteve a figurinha ' || v_sticker || ' via Pick pós-partida',
      'pick'
    );
  end loop;

  if v_username = v_match.player_a_username then
    update public.foc2026_matches set player_a_picks_completed = true where id = p_match_id;
  else
    update public.foc2026_matches set player_b_picks_completed = true where id = p_match_id;
  end if;

  update public.foc2026_matches
  set completed = true
  where id = p_match_id
    and player_a_picks_completed = true
    and player_b_picks_completed = true;
end;
$$;

